### ISSUE TITLE
Support `[contenthash]`

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/loader-utils#112]
Based on https://github.com/webpack-contrib/file-loader/issues/267

**Comment by albertfdp** [comment]
Are there any plans to fix this? Seems it breaks pretty badly if you use SRI https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/56

**Comment by evilebottnawi** [comment]
@albertfdp feel free to send PR

**Comment by rightaway** [comment]
Any contributor with knowledge of how to fix this issue and might be willing to take a look at it?

**Comment by evilebottnawi** [comment]
@rightaway We have many issues and PRs in many repos and don't have enough time for all, we are happy with any help

**Comment by edmorley** [comment]
From what I can tell it seems the `contentHash` hook is what this would need to use:
https://github.com/webpack/webpack/blob/1495b33102e2197792c5e2558e216c47ffac32fb/lib/Compilation.js#L318-L319
https://github.com/webpack/webpack/blob/1495b33102e2197792c5e2558e216c47ffac32fb/lib/Compilation.js#L2275

Presumably the implementation would need to be something similar to what `JavascriptModulesPlugin()` does?
https://github.com/webpack/webpack/blob/aecdeb35a662953285603ca09a004ee752d2fb60/lib/JavascriptModulesPlugin.js#L125-L156

**Comment by evilebottnawi** [comment]
@edmorley for loader-utils `contenthash` === `hash`

**Comment by edmorley** [comment]
I don't really understand how to relate that to my comment? Could you explain more?

Also, several of the "add contenthash support" threads that were linked to this one, were actually for plugins rather than loaders. Is this package meant to be designed for plugins as well as loaders (ie the name isn't meant to be literal), or will they need a different implementation in another shared package?

**Comment by evilebottnawi** [comment]
@edmorley [contenthash] has same implementation as `hash` for plugins and loaders
