### ISSUE TITLE
[CVE-2022-37601]/Prototype pollution found in parseQuery.js

### ISSUE THREAD

**Issue by Supraja9726** [webpack/loader-utils#212]
Prototype pollution vulnerability in function parseQuery in parseQuery.js in webpack loader-utils 2.0.0 via the name variable in parseQuery.js.

The prototype pollution vulnerability can be mitigated with several best practices described here: https://learn.snyk.io/lessons/prototype-pollution/javascript/

**Comment by JSMike** [comment]
[From the error report](https://nvd.nist.gov/vuln/detail/CVE-2022-37601) The issue is here:
https://github.com/webpack/loader-utils/blob/v2.0.2/lib/parseQuery.js#L29

Because of the following `result[name]` assignments. This report seems to want `const result = {};` to be `const result = Object.create(null);` if you're going to manipulate an object the way you are to avoid a prototype pollution exploit.

Per the reporting tool this was reported to you in: https://github.com/webpack/loader-utils/issues/212

**Comment by alexander-akait** [comment]
@JSMike Thank you, published https://github.com/webpack/loader-utils/releases/tag/v2.0.3

**Comment by Reckit075** [comment]
@JSMike Is this issue resolved in the new version or I have to overwrite pareQuery.js ?

**Comment by w3bdesign** [comment]
@JSMike 

Tried to fix this with Dependabot and I get this, so it looks like it is fixed:
 

> No security update is needed as loader-utils is no longer vulnerable
> 
> Dependabot hasn't attempted to update loader-utils as it's no longer vulnerable.

**Comment by G-Rath** [comment]
@w3bdesign if Dependabot is still showing the vulnerability as open in your codebase but giving that message, then its because you've got multiple versions of `loader-utils` in the dependency tree, some of which are vulnerable but currently [dependabot only sees the "first" one](https://github.com/dependabot/dependabot-core/issues/4701).

@alexander-akait I'm sorry I have to ask, but any chance of getting this backported to 1.x? It looks like this is commonly pulled in by [`babel-loader`](https://www.npmjs.com/package/babel-loader) who have [moved away from it as a dependency in v9](https://github.com/babel/babel-loader/pull/942) but that meant dropping webpack v4 support, and we're sadly still locked into v4 for a while longer due to setups like [`@rails/webpacker`](https://www.npmjs.com/package/@rails/webpacker) that are no longer maintained but require enough time and budget to move off that we can't just do it for all of our apps (😢)

As always I'm happy to do anything I can to make it less work for you 🙂

**Comment by ashkulz** [comment]
@alexander-akait this also affects us, the dependency tree is
```
@vue/cli-service@5.0.8
  @vue/vue-loader@15.10.0
    loader-utils@1.4.0
```
There's no branch for 1.x else I'd have submitted a PR :sweat_smile: Hopefully the upstream issue vuejs/vue-cli#7323 is actioned soon :crossed_fingers:

**Comment by ashkulz** [comment]
Thanks for the quick release of 1.4.1, @alexander-akait :tada:

**Comment by danielhaim1** [comment]
🎉

**Comment by jdgregson** [comment]
Is there a working PoC for this issue? This same pattern of `dest[foo] = src[foo]` has been marked as prototype pollution on [many](https://github.com/thlorenz/browserify-shim/issues/245#issuecomment-1279264857) [different](https://github.com/beautify-web/js-beautify/issues/2106#issuecomment-1287276067) [repositories](https://github.com/remy/nodemon/issues/2068#issuecomment-1275914612) recently. However, after [much research](https://github.com/xmldom/xmldom/issues/436#issuecomment-1307563456), I have not found the pattern to be inherently vulnerable, and a good answer [here](https://github.com/beautify-web/js-beautify/issues/2106#issuecomment-1295366484) shows that it is not.

If there is a way to exploit this I'd love to know, but I feel that this is very likely a false positive.

**Comment by theJuan1112** [comment]
I also agree that this is most likely a false positive. I went into a little more details on a [comment](https://github.com/webpack/loader-utils/pull/217#issuecomment-1332523089)t in the "fix" they did for this. The only thing I can come up that could lead to security issues is how the object created will be handled, but that is up to the apps/packages using this as a dependency to figure it out in their specific use case.

**Comment by alexander-akait** [comment]
A minimally reproducible example should be provided, firstly internally to fix the problem, then publicly

**Comment by theJuan1112** [comment]
I actually just watched the presentation for the [research paper](https://dl.acm.org/doi/pdf/10.1145/3488932.3497769) on this and the presenter specially noted that their tool/analyzer does NOT take into account context, which that is the MAIN point of doing proper security research/disclosure. This is just so bad/annoying because you are getting reports of a CRITICAL in your apps, especially for such widely used dependencies, which you are forced to check. Oh well, time to move on.

**Comment by jdgregson** [comment]
After some research over the last few months I have found that the original research is correct in finding that `dest[foo] = src[foo]` is inherently vulnerable to prototype pollution, though there is a push to call this variant "prototype poisoning". This vulnerability does not pollute the global object prototype. Rather, it poisons the prototype of the `dest` object:

```javascript
const src = JSON.parse('{"__proto__": {"polluted": true}}');
const dest = {};
Object.keys(src).forEach((key) => {dest[key] = src[key]})
window.polluted; // undefined
dest.polluted; // true
```

This can allow an attacker to bypass filters in some cases by adding hidden keys to the `dest` object.

I am not sure what the original vulnerability was in this case, but I found that [someone mentioned](https://github.com/webpack/loader-utils/pull/217#issuecomment-1315991295) the the exploit code would be a query like `{a:"1",__proto__:{"isPolluted":true}}`. 

I looked into it and found that `loader-utils` was vulnerable as the above payload resulted in prototype poisoning. However, `loader-utils` simply passed such payloads to `json5`. I investigated `json5` and found that it was the cause of the prototype poisoning, and it was fixed as [CVE-2022-46175 ](https://github.com/json5/json5/security/advisories/GHSA-9c47-m6qq-7p4h).

Whether or not the vulnerability was actually impactful given the context is another question.

**Comment by JeremyRH** [comment]
I think we agree this "prototype poisoning" is not the same as prototype pollution. It requires the code using parseQuery.js to check iterable own keys on `result` for "protected" keys then assume this check was thorough enough. It does increase the chance for vulnerabilities but should not be classified as "critical" IMO.
How do we go about adding a new common vulnerability called "prototype poisoning"?
