### ISSUE TITLE
seeing problem with `loader-urls` via `css-loader` since 0.2.17 release

### ISSUE THREAD

**Issue by mattkime** [webpack/loader-utils#70]
We're seeing a failure to resolve a module via css-loader since 0.2.17 was released. If we include 0.2.16 as a devDependency then we don't see the problem. 

I know I should build a small test case that displays the problem but we have a large webpack build. I'd rather get the word out if others are having problems.

**Comment by jhnns** [comment]
> We're seeing a failure to resolve a module via css-loader since 0.2.17 was released

This is completely vague. If you can't come up with a small test case, you could:

- give us the loader-utils version (since you're creating an issue in the loader-utils repo)
- give us your configuration for the css-loader pipeline
- give us an error message
- give us the path of the file and the request (the string given to `require()`)

Please understand that I'm closing this one until there is more information.
