### ISSUE TITLE
Empty string is rewritten as './' in urlToRequest

### ISSUE THREAD

**Issue by darrenscerri** [webpack/loader-utils#80]
Related issue: https://github.com/webpack-contrib/css-loader/issues/463

Calling `urlToRequest` with an empty string resolves to `./`. This behaviour should not be allowed, or rather keep as an empty string and let Webpack handle it.

**Comment by jhnns** [comment]
Mhmm, I think the current behavior is correct. CSS does not distinguish between`url('file.jpg')` and `url(./file.jpg)`. That's why an empty string `''` should be equivalent to `'./'`. Could you describe your use-case? Why do you have an empty `url()` statement—and how is webpack supposed to handle an empty request?

**Comment by jhnns** [comment]
Ah ok ... this was an error in the first place. What error does webpack report in this case?

**Comment by darrenscerri** [comment]
Webpack doesn't report any errors but proceeds to trying to require `'./` even if it's a JS file.

The original issue was here: https://github.com/facebookincubator/create-react-app/issues/1875. The `url('')` was a mistake but lead to a very hard-to-find bug.

Webpack currently warns if somebody does a `require('')` (https://github.com/webpack/webpack/issues/2006).

Maybe we should warn if somebody tries to rewrite `''`?

**Comment by jhnns** [comment]
Yeah, I totally see that. While transforming `''` to `'./'` is theoretically correct, it is most likely an error.

I thought about throwing an error if an empty url is passed, but that wouldn't be very pleasant to use *and* it would be a breaking change since the call needs to be wrapped in try/catch.

Maybe it's best to just keep it as it is and let webpack handle it correctly (as you suggested)... not the most beautiful solution 😞, but it would probably work.

**Comment by jhnns** [comment]
@darrenscerri Would you be up to a pull-request? Should be a small change...

**Comment by darrenscerri** [comment]
@jhnns Added pull-request
